import PageName from '@/components/PageName'
import { MenuIcon, SettingsIcon } from 'lucide-react'
import type { Metadata } from 'next'
import { Lexend } from 'next/font/google'
import './globals.css'

const lexend = Lexend({
  variable: '--font-lexend',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'SuckMyIV',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.variable} m-auto max-w-4xl antialiased`}>
        <header className="flex items-center justify-between p-4 text-neutral-900">
          <button type="button">
            <MenuIcon size={24} />
          </button>
          <PageName />
          <button type="button">
            <SettingsIcon size={24} />
          </button>
        </header>
        {children}
      </body>
    </html>
  )
}
